#!/bin/bash
arg1=$1;
arg2=$2;
while [ -z $arg1 ];do
	echo 'No has introducido ningun numero, por favor introduce 2.';
	read -p 'Introduce el primer numero: ' arg1;
	read -p 'Introduce el segundo numero: ' arg2;
done
while [ -z $arg2 ];do
	echo 'No has introducido el segundo numero.';
	read -p 'Introduce el segundo numero' arg2;
done
if [ $arg1 -gt $arg2 ];then
	echo $arg1 ' es mayor que '$arg2;
fi
if [ $arg1 -lt $arg2 ];then
	echo $arg1 ' es menor que '$arg2;
fi
if [ $arg1 -eq $arg2 ];then
	echo $arg1 ' es igual que '$arg2;
fi
