#!/bin/bash
read -p 'Introduce un numero: ' num;
while [ -z $num ];do
	read -p 'Introduce un numero: ' num;
done
resultado=$num;
for val in `seq 1 3`
do
	resultado=`expr $resultado / 2`;
	resto=`expr resultado % 2`;
	echo $resultado;
	echo $resto;
done
